---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: the-world-machine
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    install:
      - tailscale
      - mullvad-vpn
    remove:
      # Unneeded / legacy GNOME apps removed
      - gnome-system-monitor
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-window-list
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-places-status-indicator
      - gnome-classic-session 

  - type: systemd
    system:
      enabled:
        - tailscaled
        - mullvad-daemon

  - type: gnome-extensions
    install:
      - 307
      - 615
      - 6139

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - com.github.wwmm.easyeffects
      #remove:
      #  - org.gnome.eog

